export default {
  intros: [
    "Miniature{s} painted by community member {username}.",
    "Painted by community member {username}.",
    "Painted by {username} from the miniature painting discord.",
  ],
  incentives: [
    "Planning something similar?  Bring your project over to our Discord and join in the fun!",
    "Curious about the hobby?  Want to give it a go but don't know where to start?  Come on over to our Discord",
    "Been a while since you last painted and want to get back into it?  No need to do it alone! Come share the fun on our Discord",
    "Bring your backlog (or start a new one!) and join our Discord today!",
    "Like what you see?  Looked into it before but confused by brush sizes?  We've got you covered!  Head over to our Discord today",
    "Want to join in?  You can!  Painters of all skill levels are ready and waiting to go #off-topic at the drop of a hat",
    "Get feedback on your WIPs, help with colour theory, and good ole fashion encouragement in our Discord!",
    "Keep up to date with the latest miniature releases, cool Kickstarters, and awesome new paint ranges, all while hanging out with fellow hobbyists.",
    "Tips on glazing, wetblending, basing, and general backlog management (buy more minis) available in our Discord community!  Come hang out!",
    "Want to try something similar?  Not sure what colours they used?  Find out in our Discord community ",
    "Paint-alongs, bi-monthly challenges, duels, raffles and meaningless Internet points going on now, in our Discord community! All are welcome.",
    "Want to start painting but aren't sure about paints, brushes, primer, varnish, and all that complicated stuff?  No worries, we've got you covered!  Come hang out!",
    "These and more being painted right now, in the company of like-minded plastic addicts.  Build your backlog to be its best possible self, over in Discord!",
    "Curious about pinning?  Need new basing materials but not sure where to look?  We can help!  Join our Discord community!",
  ],
  hashtags: [
    "#miniatures",
    "#miniature",
    "#warhammer",
    "#warhammer40k",
    "#paintingwarhammer",
    "#tabletopgames",
    "#miniaturepainting",
    "#minipainting",
    "#gamesworkshop",
    "#malifaux",
    "#ageofsigmar",
    "#miniaturepainting",
    "#painting",
    "#wepaintminis",
    "#hobby",
    "#minis",
    "#mini",
    "#art",
    "#acrylic",
  ],
}
